"""
Stage 4 — Comment Formatter

Renders CommentGroup objects into fully-formatted comment bodies.

Supported platforms
───────────────────
  "github"  — GitHub Flavored Markdown with > [!NOTE] / > [!WARNING] /
               > [!CAUTION] admonitions and fenced code blocks.
  "gitlab"  — Standard CommonMark (no GFM admonitions); uses bold headers.
  "jira"    — Jira wiki markup (h3./h4. headings, {code} blocks, colour macros).
  "text"    — Plain ASCII for CLI output and email. No markdown.

Each platform has a _render_<platform>() method.  Adding a new platform
only requires adding one method and one entry in _RENDERERS.

Usage::

    formatter = CommentFormatter(platform="github")
    body = formatter.render(group)            # one CommentGroup → str
    summary = formatter.render_summary(       # list of evicted groups → str
        summary_groups, inline_count=14
    )
"""

from __future__ import annotations

import textwrap
from typing import Callable, Dict, List

from stage4_comments.grouper import CommentGroup
from core.models import ReviewIssue

_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🔵",
    "INFO":     "⚪",
}

_SEVERITY_RANK = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}

# GitHub admonition type per severity
_GH_ADMONITION = {
    "CRITICAL": "CAUTION",
    "HIGH":     "WARNING",
    "MEDIUM":   "NOTE",
    "LOW":      "NOTE",
    "INFO":     "TIP",
}


class CommentFormatter:
    """
    Renders CommentGroup → formatted comment body string.

    Args:
        platform: "github" | "gitlab" | "jira" | "text"
    """

    def __init__(self, platform: str = "github") -> None:
        self._platform = platform.lower()
        self._renderers: Dict[str, Callable] = {
            "github": self._render_github,
            "gitlab": self._render_gitlab,
            "jira":   self._render_jira,
            "text":   self._render_text,
        }
        if self._platform not in self._renderers:
            raise ValueError(
                f"Unknown platform '{platform}'. "
                f"Choose from: {list(self._renderers)}"
            )

    # ── Public ────────────────────────────────────────────────────────────────

    def render(self, group: CommentGroup) -> str:
        """Render one CommentGroup into a formatted body string."""
        return self._renderers[self._platform](group)

    def render_summary(
        self,
        summary_groups: List[CommentGroup],
        inline_count:   int = 0,
    ) -> str:
        """
        Render a catch-all summary comment for budget-evicted groups.

        The summary is always emitted at the PR/review level (line=0).
        """
        if not summary_groups:
            return ""
        return self._renderers[self._platform + "_summary"](
            summary_groups, inline_count
        ) if (self._platform + "_summary") in self._renderers else \
            self._render_summary_generic(summary_groups, inline_count)

    # ── GitHub ────────────────────────────────────────────────────────────────

    def _render_github(self, group: CommentGroup) -> str:
        issues = _sort_issues(group.issues)
        admonition = _GH_ADMONITION.get(group.severity, "NOTE")
        lines: List[str] = []

        if len(issues) == 1:
            issue = issues[0]
            emoji = _SEVERITY_EMOJI.get(issue.severity, "")
            lines.append(
                f"> [!{admonition}]\n"
                f"> {emoji} **{issue.title}** `{issue.rule_id}` · "
                f"{issue.severity}"
            )
            if issue.description:
                for desc_line in issue.description.strip().splitlines():
                    lines.append(f"> {desc_line}")
            if issue.suggestion:
                lines.append(f">\n> **Suggestion:** {issue.suggestion.strip()}")
        else:
            lines.append(
                f"> [!{admonition}]\n"
                f"> **{len(issues)} issues** in this area "
                f"(dominant: {group.severity})"
            )
            for issue in issues:
                emoji = _SEVERITY_EMOJI.get(issue.severity, "")
                lines.append(
                    f">\n> {emoji} **{issue.title}** `{issue.rule_id}` "
                    f"· line {issue.start_line} · {issue.severity}"
                )
                if issue.description:
                    short_desc = issue.description.strip().splitlines()[0][:120]
                    lines.append(f">   {short_desc}")
                if issue.suggestion:
                    lines.append(
                        f">   _Fix:_ {issue.suggestion.strip().splitlines()[0][:120]}"
                    )

        lines.append(
            f"\n<sub>Generated by code-reviewer-agent · "
            f"{', '.join(i.rule_id for i in issues)}</sub>"
        )
        return "\n".join(lines)

    # ── GitLab ────────────────────────────────────────────────────────────────

    def _render_gitlab(self, group: CommentGroup) -> str:
        issues = _sort_issues(group.issues)
        lines: List[str] = []

        for issue in issues:
            emoji = _SEVERITY_EMOJI.get(issue.severity, "")
            lines.append(
                f"**{emoji} {issue.title}** (`{issue.rule_id}`) — "
                f"*{issue.severity}* at line {issue.start_line}"
            )
            if issue.description:
                lines.append(f"\n{issue.description.strip()}")
            if issue.suggestion:
                lines.append(f"\n**Suggestion:** {issue.suggestion.strip()}")
            lines.append("\n---")

        lines.append(
            f"\n_Generated by code-reviewer-agent · "
            f"{', '.join(i.rule_id for i in issues)}_"
        )
        return "\n".join(lines)

    # ── Jira ──────────────────────────────────────────────────────────────────

    def _render_jira(self, group: CommentGroup) -> str:
        issues = _sort_issues(group.issues)
        lines: List[str] = []

        _jira_severity_colour = {
            "CRITICAL": "red",
            "HIGH":     "orange",
            "MEDIUM":   "yellow",
            "LOW":      "blue",
            "INFO":     "gray",
        }

        for issue in issues:
            colour = _jira_severity_colour.get(issue.severity, "gray")
            lines.append(
                f"h4. {{{colour}|{issue.severity}}} {issue.title} "
                f"({issue.rule_id}) — line {issue.start_line}"
            )
            if issue.description:
                lines.append(issue.description.strip())
            if issue.suggestion:
                lines.append(f"*Suggestion:* {issue.suggestion.strip()}")
            lines.append("")

        lines.append(
            f"_Generated by code-reviewer-agent · "
            f"{', '.join(i.rule_id for i in issues)}_"
        )
        return "\n".join(lines)

    # ── Plain text ────────────────────────────────────────────────────────────

    def _render_text(self, group: CommentGroup) -> str:
        issues = _sort_issues(group.issues)
        sep    = "─" * 60
        lines: List[str] = [sep]

        for issue in issues:
            lines.append(
                f"[{issue.severity}] {issue.rule_id}: {issue.title} "
                f"(line {issue.start_line})"
            )
            if issue.description:
                wrapped = textwrap.fill(
                    issue.description.strip(), width=72, initial_indent="  ",
                    subsequent_indent="  ",
                )
                lines.append(wrapped)
            if issue.suggestion:
                lines.append(f"  Fix: {issue.suggestion.strip()}")
            lines.append("")

        lines.append(sep)
        return "\n".join(lines)

    # ── Summary comment ───────────────────────────────────────────────────────

    def _render_summary_generic(
        self,
        summary_groups: List[CommentGroup],
        inline_count:   int,
    ) -> str:
        """Fallback summary renderer used by all platforms."""
        all_issues = [i for g in summary_groups for i in g.issues]
        all_issues = _sort_issues(all_issues)

        if self._platform == "github":
            lines = [
                "> [!NOTE]",
                f"> **Additional findings** ({len(all_issues)} issues not shown inline)",
                f"> {inline_count} issue(s) already shown as inline comments.",
                ">",
            ]
            for issue in all_issues:
                emoji = _SEVERITY_EMOJI.get(issue.severity, "")
                lines.append(
                    f"> {emoji} `{issue.rule_id}` **{issue.title}** "
                    f"— {issue.file_path}:{issue.start_line} · {issue.severity}"
                )
            lines.append(
                "\n<sub>Generated by code-reviewer-agent</sub>"
            )
        elif self._platform == "jira":
            lines = [
                f"h3. Additional findings ({len(all_issues)} issues)",
                f"{inline_count} issue(s) already added as inline comments.",
                "",
            ]
            for issue in all_issues:
                lines.append(
                    f"* [{issue.severity}] {issue.rule_id}: {issue.title} "
                    f"— {issue.file_path}:{issue.start_line}"
                )
        else:
            lines = [
                f"=== Additional findings ({len(all_issues)} issues) ===",
                f"{inline_count} issue(s) already shown inline.",
                "",
            ]
            for issue in all_issues:
                lines.append(
                    f"  [{issue.severity}] {issue.rule_id}: {issue.title} "
                    f"({issue.file_path}:{issue.start_line})"
                )

        return "\n".join(lines)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _sort_issues(issues: List[ReviewIssue]) -> List[ReviewIssue]:
    """Sort issues CRITICAL-first, then by line."""
    return sorted(
        issues,
        key=lambda i: (_SEVERITY_RANK.get(i.severity, 99), i.start_line),
    )
