"""
GitHub REST API client.

Handles two operations needed by the code reviewer:

  1. get_pr_info(owner, repo, pr_number)
       Returns base_sha, head_sha, and the diff URL so Stage 1 can do
       diff-aware ingestion of only the files changed in the PR.

  2. post_review(owner, repo, pr_number, commit_sha, comments, summary_body)
       Creates a single pull-request review with all inline comments in one
       API call — avoids the rate-limit and notification spam of individual
       per-line comment calls.

Auth:
  Set GITHUB_TOKEN env var or pass token= explicitly.
  No token → read-only operations (get_pr_info) work on public repos;
  post_review will return 401.

Usage::

    gh = GitHubTool(token=os.getenv("GITHUB_TOKEN", ""))

    info = gh.get_pr_info("owner", "repo", 42)
    # info["base_sha"], info["head_sha"], info["head_ref"]

    gh.post_review(
        owner="owner", repo="repo", pr_number=42,
        commit_sha=info["head_sha"],
        comments=state["comments"],
        summary_body=state.get("report_markdown", ""),
    )
"""

from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

from core.models import ReviewComment

logger = logging.getLogger(__name__)

_GH_API = "https://api.github.com"


class GitHubTool:
    """
    Thin wrapper around the GitHub v3 REST API.

    Uses only stdlib `urllib` — no extra dependencies required.
    """

    def __init__(self, token: str = "") -> None:
        self._token = token or os.getenv("GITHUB_TOKEN", "")

    # ── Public ────────────────────────────────────────────────────────────────

    def get_pr_info(self, owner: str, repo: str, pr_number: int) -> Dict[str, Any]:
        """
        Fetch PR metadata.

        Returns dict with keys:
            base_sha, head_sha, head_ref, base_ref,
            title, number, state, changed_files
        """
        url  = f"{_GH_API}/repos/{owner}/{repo}/pulls/{pr_number}"
        data = self._get(url)
        return {
            "base_sha":     data["base"]["sha"],
            "head_sha":     data["head"]["sha"],
            "base_ref":     data["base"]["ref"],
            "head_ref":     data["head"]["ref"],
            "title":        data.get("title", ""),
            "number":       data.get("number", pr_number),
            "state":        data.get("state", ""),
            "changed_files":data.get("changed_files", 0),
        }

    def post_review(
        self,
        owner:        str,
        repo:         str,
        pr_number:    int,
        commit_sha:   str,
        comments:     List[ReviewComment],
        summary_body: str = "",
    ) -> Dict[str, Any]:
        """
        Create a pull-request review with all inline comments in one API call.

        Only `inline` comment_type ReviewComment objects are posted as line
        comments.  `summary` and `file_level` types are folded into the PR
        review body.

        Args:
            owner, repo:    Repository co-ordinates.
            pr_number:      PR number to comment on.
            commit_sha:     Head commit SHA (required by the GitHub reviews API).
            comments:       List[ReviewComment] from Stage 4.
            summary_body:   Text for the overall PR review body (Stage 5 report).

        Returns:
            The created review object dict from the GitHub API.

        Raises:
            RuntimeError on API error.
        """
        inline = [c for c in comments if c.comment_type == "inline" and c.line > 0]
        extra  = [c for c in comments if c.comment_type != "inline" or c.line == 0]

        # Fold extra comments into the summary body
        full_body = summary_body
        for c in extra:
            if c.body:
                full_body += f"\n\n---\n{c.body}"

        gh_comments = []
        for c in inline:
            gh_comment: Dict[str, Any] = {
                "path": c.file_path,
                "body": c.body,
            }
            # Use line range if start != end, otherwise single line
            if c.end_line > c.line:
                gh_comment["start_line"] = c.line
                gh_comment["line"]       = c.end_line
                gh_comment["side"]       = "RIGHT"
                gh_comment["start_side"] = "RIGHT"
            else:
                gh_comment["line"] = c.line
                gh_comment["side"] = "RIGHT"
            gh_comments.append(gh_comment)

        payload = {
            "commit_id": commit_sha,
            "body":      full_body or "Code review generated by code-reviewer-agent.",
            "event":     "COMMENT",
            "comments":  gh_comments,
        }

        url = f"{_GH_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
        result = self._post(url, payload)
        logger.info(
            "[GitHubTool] Posted review #%s to %s/%s PR#%d (%d inline comments)",
            result.get("id"), owner, repo, pr_number, len(gh_comments),
        )
        return result

    @staticmethod
    def parse_repo_url(repo_url: str):
        """
        Extract (owner, repo) from a GitHub URL.

        Handles:
          https://github.com/owner/repo
          https://github.com/owner/repo.git
          git@github.com:owner/repo.git
        """
        import re
        url = repo_url.rstrip("/").removesuffix(".git")
        m = re.search(r"github\.com[:/]([^/]+)/([^/]+)$", url)
        if not m:
            raise ValueError(f"Cannot parse GitHub URL: {repo_url}")
        return m.group(1), m.group(2)

    # ── Private HTTP helpers ──────────────────────────────────────────────────

    def _headers(self) -> Dict[str, str]:
        """Build the base request headers, adding a Bearer Authorization header when a token is set."""
        h = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}
        if self._token:
            h["Authorization"] = f"Bearer {self._token}"
        return h

    def _get(self, url: str) -> Dict:
        """
        Issue an authenticated GET and return the parsed JSON body.

        Raises:
            RuntimeError: Wrapping the response body on any HTTP error.
        """
        req = urllib.request.Request(url, headers=self._headers())
        try:
            with urllib.request.urlopen(req, timeout=20) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace")
            raise RuntimeError(f"GitHub GET {url} → {exc.code}: {body}") from exc

    def _post(self, url: str, payload: Dict) -> Dict:
        """
        Issue an authenticated JSON POST and return the parsed JSON body.

        Raises:
            RuntimeError: Wrapping the response body on any HTTP error.
        """
        data = json.dumps(payload).encode()
        req  = urllib.request.Request(
            url, data=data, headers={**self._headers(), "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace")
            raise RuntimeError(f"GitHub POST {url} → {exc.code}: {body}") from exc
